### ISSUE TITLE
Suggestion: Add go-merkletree to awesome-go

### ISSUE THREAD

**Issue by elliotwutingfeng** [txaty/go-merkletree#14]
Hi, you might want to consider adding go-merkletree to [awesome-go](https://github.com/avelino/awesome-go), it appears to meet all their criteria. :sunglasses:

**Comment by txaty** [comment]
Thanks for your suggestion.
Actually, I have submitted the PR to awesome-go a few days ago :)
https://github.com/avelino/awesome-go/pull/4393

**Comment by elliotwutingfeng** [comment]
I see, well, good luck!
